binary_sensor:
  - platform: mqtt
    name: "Doorbell button"
    state_topic: "doorbell/input/button"
    payload_on: "On"
    payload_off: "Off"

input_boolean:
  doorbell:
    name: Doorbell
    initial: off
    icon: mdi:bell-ring

input_select:
  doorbell:
    name: Doorbell
    options:
      - ring-on
      - ring-off
    initial: ring-on
    icon: mdi:bell-ring

light:
  #entity_id: doorbell_led_light
  platform: mqtt
  command_topic: "doorbell/rgb/switch"
  rgb_command_topic: "doorbell/rgb/color"
  name: Doorbell LED

automation:
  - alias: Door knob pushed in
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.doorbell_button
        to: "on"
    action:
      - alias: "Turn ON"
        service: input_boolean.turn_on
        entity_id: input_boolean.doorbell
  - alias: Doorbell rings!
    initial_state: true
    trigger:
      platform: state
      entity_id: input_boolean.doorbell
      to: "on"
    action:
      - service: script.turn_on
        entity_id: script.notify
  - alias: Doorbell rings but is off!
    initial_state: true
    condition:
      condition: template
      value_template: "{{ is_state('input_select.doorbell', 'ring-off') }}"
    trigger:
      platform: state
      entity_id: input_boolean.doorbell
      to: "on"
    action:
      - alias: "Turn off sound"
        service: input_boolean.turn_off
        entity_id: input_boolean.doorbell #turn input boolean back off so nothing happened
      - alias: "Change icon in card"
        service: input_select.turn_off
        entity_id: input_select.doorbell
  - alias: Doorbell off
    initial_state: true
    trigger:
      platform: state
      entity_id: input_boolean.doorbell
      to: "off"
    action:
      - alias: "Go to default view1"
        event: browser_command
        event_data:
          command: navigate
          navigation_path: /lovelace/default_view
      - alias: "Restore sonos"
        service: sonos.restore
        data:
          with_group: true
  - alias: Doorbell on every morning
    initial_state: true
    trigger:
      platform: time
      at: "7:30:00"
    action:
      service: input_select.select_option
      data:
        entity_id: input_select.doorbell
        option: ring-on

script:
  notify:
    sequence:
      - service: browser_mod.popup
        data:
          title: Someone is calling
          hide_header: true
          large: true
          card:
            type: custom:doorpi-card
            camera_entity: camera.doorbell_camera
            doorpi:
              url: https://10.180.2.241
              #url: https://192.168.100.121
